services:
# MySQL8
  mysql8:
    image: mysql:8.0.29
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./script/mysql/:/docker-entrypoint-initdb.d/
    ports:
      - "13306:3306"
  redis:
    image: docker.io/bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
  etcd:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      #      客户端通信接口
      - 2379:2379
      #      集群节点通信端口
      - 2380:2380
  etcdkeeper:
    image: evildecay/etcdkeeper:latest
    container_name: "etcdkeeper"
    #    environment:
    #      HOST: "0.0.0.0"
    ports:
      - 12000:8080
    depends_on:
      - etcd
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
#    network_mode: host
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"